name: Build
on:
  [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/stoneddiscord/m68k_bare_metal:master
    strategy:
      matrix:
        version: [50B_1MB, 50B_2MB, 50A_1MB, ALT_1MB, UHG_1MB, ROTE_512KB, TEST_1MB]
    steps:
    - uses: actions/checkout@v6
    - name: Build
      run: |
        make crt
        make VERSION=${{ matrix.version }} xc
    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        name: Loader-${{ matrix.version }}
        path: Loader.xc
